title: Aagam Shah
logo: "/profile.jpg?raw=true"
description:
 Fullstack Developer
  <br><br>
  <a href="mailto:aagamshah508@gmail.com">aagamshah508@gmail.com </a>
  <br>
  <a href="www.linkedin.com/in/aagam-shah-177968170">LinkedIn Profile</a>
  <br>
  <a href="https://github.com/aagamshah1410">Gihub</a> 
theme: jekyll-theme-minimal
